# Generated by Django 6.0.6 on 2026-06-09 10:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rybnik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazev", models.CharField(max_length=255)),
                ("vodni_plocha", models.FloatField()),
                (
                    "polygon",
                    django.contrib.gis.db.models.fields.PolygonField(srid=4326),
                ),
            ],
            options={
                "verbose_name": "Rybník",
                "verbose_name_plural": "Rybníky",
            },
        ),
    ]
