# Generated by Django 6.0.6 on 2026-06-09 11:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rybniky", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vlastnik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jmeno", models.CharField(max_length=255)),
                ("telefon", models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name="rybnik",
            name="nazev",
            field=models.CharField(max_length=255, verbose_name="Název"),
        ),
        migrations.AlterField(
            model_name="rybnik",
            name="polygon",
            field=django.contrib.gis.db.models.fields.PolygonField(
                srid=4326, verbose_name="Polygon"
            ),
        ),
        migrations.AlterField(
            model_name="rybnik",
            name="vodni_plocha",
            field=models.FloatField(verbose_name="Vodní plocha (ha)"),
        ),
    ]
