# Generated by Django 6.0.6 on 2026-06-09 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rybniky", "0002_vlastnik_alter_rybnik_nazev_alter_rybnik_polygon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rybnik",
            name="vlastnik",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rybniky.vlastnik",
            ),
        ),
    ]
