# Generated by Django 6.0.6 on 2026-06-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rybniky", "0003_rybnik_vlastnik"),
    ]

    operations = [
        migrations.CreateModel(
            name="OdpovednaOsoba",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jmeno", models.CharField(max_length=255)),
                ("telefon", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Odpovědná osoba",
                "verbose_name_plural": "Odpovědné osoby",
            },
        ),
        migrations.AlterModelOptions(
            name="vlastnik",
            options={"verbose_name": "Vlastník", "verbose_name_plural": "Vlastníci"},
        ),
    ]
