# Generated by Django 6.0.6 on 2026-06-09 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rybniky", "0004_odpovednaosoba_alter_vlastnik_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="rybnik",
            name="odpovedna_osoba",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rybniky.odpovednaosoba",
            ),
        ),
    ]
