# Generated by Django 6.0.6 on 2026-06-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rybniky", "0005_rybnik_odpovedna_osoba"),
    ]

    operations = [
        migrations.CreateModel(
            name="TBD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datum", models.DateTimeField(verbose_name="Datum a čas")),
                (
                    "mimoradna_obchuzka",
                    models.BooleanField(
                        default=False, verbose_name="Mimorádná obchůzka"
                    ),
                ),
                ("oblacnost", models.CharField(max_length=255, verbose_name="Oblast")),
                (
                    "vitr",
                    models.CharField(
                        default="bezvětří", max_length=255, verbose_name="Vítr"
                    ),
                ),
                ("teplota", models.FloatField(verbose_name="Teplota °C")),
                ("srazky", models.FloatField(default=0, verbose_name="Srážky (mm)")),
                (
                    "normalni_stav_hladiny",
                    models.BooleanField(
                        default=True, verbose_name="Normální stav hladiny"
                    ),
                ),
                (
                    "rozdil_stavu_hladiny",
                    models.IntegerField(
                        default=0, verbose_name="Rozdíl stavu hladiny (cm)"
                    ),
                ),
                (
                    "zavady",
                    models.CharField(
                        default=False, max_length=255, verbose_name="Závady"
                    ),
                ),
                (
                    "navrh_uprav",
                    models.TextField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Návrh úprav v případě závad",
                    ),
                ),
                (
                    "poznamka",
                    models.CharField(
                        blank=True,
                        default=False,
                        max_length=255,
                        null=True,
                        verbose_name="Poznámka",
                    ),
                ),
                (
                    "podpis",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="podpisy",
                        verbose_name="Podpis",
                    ),
                ),
            ],
        ),
    ]
