# Generated by Django 6.0.6 on 2026-06-09 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rybniky", "0006_tbd"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tbd",
            options={"verbose_name": "TBD", "verbose_name_plural": "TBD"},
        ),
        migrations.RemoveField(
            model_name="tbd",
            name="datum",
        ),
        migrations.AddField(
            model_name="tbd",
            name="rybnik",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="rybniky.rybnik",
            ),
            preserve_default=False,
        ),
    ]
