# Generated by Django 6.0.6 on 2026-06-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rybniky", "0007_alter_tbd_options_remove_tbd_datum_tbd_rybnik"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tbd",
            name="oblacnost",
            field=models.CharField(max_length=255, verbose_name="Oblačnost"),
        ),
        migrations.AlterField(
            model_name="tbd",
            name="zavady",
            field=models.BooleanField(
                default=False, max_length=255, verbose_name="Závady"
            ),
        ),
    ]
