# Generated by Django 6.0.6 on 2026-06-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rybniky", "0008_alter_tbd_oblacnost_alter_tbd_zavady"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tbd",
            name="navrh_uprav",
            field=models.TextField(
                blank=True, null=True, verbose_name="Návrh úprav v případě závad"
            ),
        ),
        migrations.AlterField(
            model_name="tbd",
            name="poznamka",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Poznámka"
            ),
        ),
    ]
