# Generated by Django 6.0.6 on 2026-06-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rybniky", "0009_alter_tbd_navrh_uprav_alter_tbd_poznamka"),
    ]

    operations = [
        migrations.AddField(
            model_name="rybnik",
            name="obec",
            field=models.CharField(default=1, max_length=255, verbose_name="Obec"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rybnik",
            name="okres",
            field=models.CharField(default=1, max_length=255, verbose_name="Okres"),
            preserve_default=False,
        ),
    ]
