# Generated by Django 6.0.6 on 2026-06-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rybniky", "0011_tbd_datum"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rybnik",
            name="vodni_plocha",
        ),
        migrations.AddField(
            model_name="rybnik",
            name="charakter",
            field=models.CharField(
                choices=[
                    ("silne", "Silně průtočný"),
                    ("slabe", "Slabě průtočný"),
                    ("nebezky", "Nebezký"),
                ],
                default=1,
                max_length=255,
                verbose_name="Charakter rybníka",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rybnik",
            name="hloubka",
            field=models.FloatField(default=1, verbose_name="Hloubka (m)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rybnik",
            name="katastralni_obec",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Katastrální obec"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rybnik",
            name="katastralni_vodni_plocha",
            field=models.FloatField(
                default=1, verbose_name="Katastrální vodní plocha (ha)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rybnik",
            name="kraj",
            field=models.CharField(default=1, max_length=255, verbose_name="Kraj"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rybnik",
            name="parcely",
            field=models.CharField(default=1, max_length=255, verbose_name="Parcely"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rybnik",
            name="zatopena_vodni_plocha",
            field=models.FloatField(
                default=1, verbose_name="Zatopená vodní plocha (ha)"
            ),
            preserve_default=False,
        ),
    ]
