# Generated by Django 6.0.6 on 2026-06-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rybniky", "0012_remove_rybnik_vodni_plocha_rybnik_charakter_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rybnik",
            name="obec",
        ),
    ]
