# Generated by Django 6.0.6 on 2026-06-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rybniky", "0013_remove_rybnik_obec"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rybnik",
            name="parcely",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Parcely"
            ),
        ),
    ]
