# Generated by Django 6.0.6 on 2026-06-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rybniky", "0014_alter_rybnik_parcely"),
    ]

    operations = [
        migrations.AddField(
            model_name="rybnik",
            name="pouziti",
            field=models.CharField(
                choices=[
                    ("vytaznik", "Výtažník"),
                    ("komora", "Komora"),
                    ("hlavni", "Hlavní rybník"),
                ],
                default=1,
                max_length=255,
                verbose_name="Použití",
            ),
            preserve_default=False,
        ),
    ]
