# Generated by Django 6.0.6 on 2026-06-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rybniky", "0015_rybnik_pouziti"),
    ]

    operations = [
        migrations.AddField(
            model_name="rybnik",
            name="doba_nahaneni",
            field=models.IntegerField(default=5, verbose_name="Doba náhánění (dny)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rybnik",
            name="doba_vypousteni",
            field=models.IntegerField(default=5, verbose_name="Doba výpouštění (dny)"),
            preserve_default=False,
        ),
    ]
