# Generated by Django 6.0.6 on 2026-06-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rybniky", "0016_rybnik_doba_nahaneni_rybnik_doba_vypousteni"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ryba",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jmeno", models.CharField(max_length=255)),
                ("znacka", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Ryba",
                "verbose_name_plural": "Ryby",
            },
        ),
    ]
