# Generated by Django 6.0.6 on 2026-06-09 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rybniky", "0017_ryba"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produkce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datum", models.DateField(verbose_name="Datum")),
                (
                    "nasazeno_vyloveno",
                    models.CharField(
                        choices=[("nasazeno", "Nasazeno"), ("vyloveno", "Vyloveno")],
                        max_length=255,
                        verbose_name="Nasazeno/vyloveno",
                    ),
                ),
                (
                    "stari",
                    models.PositiveSmallIntegerField(verbose_name="Stáří (roky)"),
                ),
                (
                    "ks",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Ks"
                    ),
                ),
                (
                    "hmotnost",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Hmotnost (ks)"
                    ),
                ),
                (
                    "cena_kg",
                    models.FloatField(blank=True, null=True, verbose_name="Cena za kg"),
                ),
                (
                    "ryba",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rybniky.ryba"
                    ),
                ),
                (
                    "rybnik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rybniky.rybnik"
                    ),
                ),
            ],
            options={
                "verbose_name": "Produkce",
                "verbose_name_plural": "Produkce",
            },
        ),
    ]
