# Generated by Django 6.0.6 on 2026-06-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rybniky", "0018_produkce"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produkce",
            name="cena_kg",
            field=models.IntegerField(blank=True, null=True, verbose_name="Cena za kg"),
        ),
        migrations.AlterField(
            model_name="produkce",
            name="hmotnost",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Hmotnost (kg)"
            ),
        ),
        migrations.AlterField(
            model_name="produkce",
            name="ks",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Ks"),
        ),
        migrations.AlterField(
            model_name="produkce",
            name="stari",
            field=models.PositiveIntegerField(verbose_name="Stáří (roky)"),
        ),
    ]
