# Generated by Django 6.0.6 on 2026-06-09 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rybniky", "0019_alter_produkce_cena_kg_alter_produkce_hmotnost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produkce",
            name="puvod",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Původ"
            ),
        ),
        migrations.AddField(
            model_name="produkce",
            name="zdroj",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="zdroj_produktu",
                to="rybniky.rybnik",
                verbose_name="Zdroj",
            ),
        ),
    ]
