# Generated by Django 6.0.6 on 2026-06-09 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rybniky", "0020_produkce_puvod_produkce_zdroj"),
    ]

    operations = [
        migrations.CreateModel(
            name="PracovniNaklady",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Datum")),
                ("cas", models.PositiveSmallIntegerField(verbose_name="Čas (hodiny)")),
                (
                    "popis_prace",
                    models.CharField(max_length=255, verbose_name="Popis práce"),
                ),
                ("najete_km", models.IntegerField(verbose_name="Najeté km")),
                (
                    "rybnik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rybniky.rybnik"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pracovní náklady",
                "verbose_name_plural": "Pracovní náklady",
            },
        ),
    ]
