# Generated by Django 6.0.6 on 2026-06-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rybniky", "0021_pracovninaklady"),
    ]

    operations = [
        migrations.AlterField(
            model_name="odpovednaosoba",
            name="jmeno",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="odpovednaosoba",
            name="telefon",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="vlastnik",
            name="jmeno",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="vlastnik",
            name="telefon",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
