# Generated by Django 6.0.6 on 2026-06-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rybniky", "0022_alter_odpovednaosoba_jmeno_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rybnik",
            name="nazev",
            field=models.CharField(max_length=255, unique=True, verbose_name="Název"),
        ),
    ]
