# Generated by Django 6.0.6 on 2026-06-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rybniky", "0023_alter_rybnik_nazev"),
    ]

    operations = [
        migrations.AddField(
            model_name="produkce",
            name="rychlenka",
            field=models.BooleanField(default=False, verbose_name="Rychlenka"),
        ),
    ]
